name: Docker AIService
on:
  workflow_call: {}
  workflow_dispatch: {}
  release:
    types:
      - released
jobs:
  docker-web:
    name: Docker Web
    uses: Onebrief/actions/.github/workflows/reusable-docker-build.yml@main
    secrets: inherit
    with:
      repository: onebrief/langfuse-ob-web
      dockerfile: web/Dockerfile
      context: .
      # Only build for amd64
      platforms: '[{"arch":"amd64","runner":"stepsecurity-x64"}]'

  docker-worker:
    name: Docker Worker  
    uses: Onebrief/actions/.github/workflows/reusable-docker-build.yml@main
    secrets: inherit
    with:
      repository: onebrief/langfuse-ob-worker
      dockerfile: worker/Dockerfile
      context: .
      # Only build for amd64
      platforms: '[{"arch":"amd64","runner":"stepsecurity-x64"}]'
